version: "3.1"
services:
  nginx:
    build: ./build/nginx
    restart: always
    container_name: square-of-squares-nginx
    ports:
      - "80:80"
  app:
    build: .
    restart: always
    container_name: square-of-squares-app
    ports:
      - "8888:8888"
  mysql:
    image: mysql:5.7
    container_name: square-of-squares-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "square-of-squares"
      MYSQL_USER: "square-of-squares"
      MYSQL_PASSWORD: "vitt@!"
      MYSQL_ROOT_PASSWORD: "vitt@!root"
    expose:
      - "3306"
    volumes:
      - data_square-of-squares:/var/lib/mysql
volumes:
  data_square-of-squares: